version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file data.yaml --s3-bucket aadhri-test-buck
                                   --output-template-file outputdata.yaml   
  build:
    commands:
      - mkdir -p lambdatest
      - mv -f Lambda/index.js lambdatest/
      - cd lambdatest
      - pwd
      - ls
      - zip -r test1.zip *
      - ls
      - aws s3 cp test1.zip s3://aadhri-test-buck/
      - cd ..
artifacts:
  type: zip
  files:
    - data.yaml
    - outputdata.yaml
