version: 0.2
phases:
  install:
    commands:
      - mkdir -p lambdatest
      - mv -f Lambda/index.js lambdatest/
      - zip -r lambdatest/test1.zip *
      - aws s3 cp lambdatest/test1.zip s3://aadhri-test-buck/
      - ./check-s3-object-version.sh
      - aws cloudformation package --template-file data.yaml --s3-bucket aadhri-test-buck
                                   --output-template-file outputdata.yaml   
  build:
    commands:
artifacts:
  type: zip
  files:
    - data.yaml
    - outputdata.yaml
