version: 0.1
phases:
  install:
    commands:
      - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
      - unzip awscli-bundle.zip
      - sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - ./awscli-bundle/install -h
      - mkdir test
      - cp -R Lambda/index.js test/
      - cd test
      - zip -r test1.zip .
      - cd ..
      - aws s3 sync ./test/test1.zip s3://aadhri-test-buck/
      - aws cloudformation package --template-file data.yaml --s3-bucket aadhri-test-buck
                                   --output-template-file outputdata.yaml   
artifacts:
  type: zip
  files:
    - data.yaml
    - outputdata.yaml
