services:
# A Docker web service
- type: web
  name: webdis
  env: docker
  repo: https://github.com/aarondaniel0110/render-webapp1.git # optional
  plan: standard              # optional
  branch: master              # optional (uses repo default)
  healthCheckPath: /
